module Main where

import System.Exit (exitFailure)

import qualified Problem01
import qualified Problem02

main = do
    putStrLn "This test always fails!"
    exitFailure